//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Досуг.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int NumberId { get; set; }
        public int UserRole { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Patronymic { get; set; }
        public int Gender { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Birthday { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    
        public virtual UserGender UserGender { get; set; }
        public virtual UserRole UserRole1 { get; set; }
    }
}
